export const products = [
  {
    id: 1,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
  {
    id: 2,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
  {
    id: 3,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
  {
    id: 4,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
  {
    id: 5,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
  {
    id: 6,
    availableInvestmentCategoryCode: "agrolyfe",
    availableInvestmentCategoryName: "Agrolyfe",
    canCustomerInvest: true,
    canCustomerInvestInOilvest: false,
    code: "agrolyfe_land_lag_001",
    country: "NG",
    createdOn: "2020-09-09T00:52:11.0928003",
    description: "Agrolyfe Lag",
    duration: 12,
    frequency: "none",
    frequencyDurations: [],
    imageURL: "https://oxfordvestapi.azurewebsites.net/Docs/AvailableInvestments/mortgage_v1.jpeg",
    isDeleted: false,
    isVisible: true,
    managementFee: 10,
    maxFrequencyDuration: 0,
    maximumAmount: 100000000,
    minFrequencyDuration: 0,
    minimumAmount: 100000,
    modifiedBy: null,
    modifiedOn: "0001-01-01T00:00:00",
    name: "agrolyfe_land_lag_001 - (20.00)",
    newInterestRate: 20,
    oldInterestRate: 20,
    percentageUpfront: 0,
    percentageUpfrontDuerationInMonths: 0,
    state: "Lagos",
    stock: 50,
  },
];
